addLayer("ltf", {
    name: "Low Taper Fade", // Full name of the layer
    symbol: "LTF", // Symbol displayed on the tree
    position: 0, // Position in the tree
    startData() {
        return {
            unlocked: true,
            points: new Decimal(0), // Prestige points for this layer
        };
    },
    color: "#1E90FF", // A stylish blue color for the layer
    requires: new Decimal(10), // Points required to gain this layer
    resource: "low taper fade points", // Name of the resource generated by this layer
    baseResource: "points", // Resource used to gain prestige points
    baseAmount() { return player.points; }, // Current amount of baseResource
    type: "normal", // Standard prestige layer type
    exponent: 0.5, // Scaling factor for prestige points

    gainMult() { // Multiplicative bonus to prestige point gain
        let mult = new Decimal(1);
        if (hasUpgrade("ltf", 12)) mult = mult.times(2); // Example: Double gains with an upgrade
        return mult;
    },

    gainExp() { // Exponential bonus to prestige point gain
        return new Decimal(1); // Default is no additional exponential scaling
    },

    row: 0, // Row in the tree (0 = top row)
    hotkeys: [
        { key: "l", description: "L: Reset for style points", onPress() { if (canReset(this.layer)) doReset(this.layer); } },
    ],

    upgrades: {
        11: {
            title: "Starter Comb",
            description: "Multiply point gain by 2.",
            cost: new Decimal(2),
            effect() {
                return new Decimal(2); // Multiplier applied to points
            },
            effectDisplay() { return "x" + format(this.effect()); }, // Displays the effect (e.g., "x2")
        },
        12: {
            title: "Advanced Clippers",
            description: "Style points multiply prestige gains.",
            cost: new Decimal(5),
            unlocked() { return hasUpgrade("ltf", 11); }, // Unlock after upgrade 11
            effect() {
                return player[this.layer].points.add(1).pow(0.4); // Scales with style points
            },
            effectDisplay() { return "x" + format(this.effect()); },
        },
    },

    milestones: {
        0: {
            requirementDescription: "10 Style Points",
            effectDescription: "Keep all upgrades on reset.",
            done() { return player.ltf.points.gte(10); },
        },
    },

    buyables: {
        11: {
            title: "Precision Clippers",
            cost(x) { return new Decimal(10).times(Decimal.pow(2, x)); }, // Scaling cost
            effect(x) { return Decimal.pow(1.5, x); }, // Multiplier effect
            display() { return `Increase point gain by x${format(this.effect())}<br>Cost: ${format(this.cost())} style points`; },
            canAfford() { return player.ltf.points.gte(this.cost()); },
            buy() {
                player.ltf.points = player.ltf.points.sub(this.cost());
                addBuyables(this.layer, 11, 1);
            },
        },
    },

    tabFormat: {
        "Main Tab": {
            content: [
                "main-display",
                "prestige-button",
                "resource-display",
                "upgrades",
                "milestones",
                "buyables",
            ],
        },
        "About": {
            content: [
                ["raw-html", () => "The Low Taper Fade Haircut is all about precision and style. Prestige in this layer to show off your grooming skills!"],
            ],
        },
    },
});
